
import apiStrapi from '@/api/apiStrapi';
import { useQuery } from '@tanstack/vue-query';
import type { PurpleAttributes } from '../interfaces/homePage';
import type { HomePage } from '../interfaces/homePage';



//const infoMain = ref([])

const getData = async ():Promise< PurpleAttributes > => {

  const resp = await apiStrapi.get< HomePage >( '/home?populate=*' )// Generated by https://quicktype.io
  return  resp.data.data.attributes
}

export const useMain =  ( ) => {

  
    
    const { isLoading ,data:infoMain} = useQuery(
      ['mainMenu'],
      getData,
      
    )
      
    
    
    return {
      isLoading,
      infoMain
    }
}