// Generated by https://quicktype.io

export interface HomePage {
  data: HomePageData;
  meta: Meta;
}

export interface HomePageData {
  id:         number;
  attributes: PurpleAttributes;
}

export interface PurpleAttributes {
  createdAt:    string;
  updatedAt:    string;
  publishedAt:  string;
  tittleButton: string;
  grayScale:    boolean;
  imagen:       Imagen;
}

export interface Imagen {
  data: ImagenData;
}

export interface ImagenData {
  id:         number;
  attributes: FluffyAttributes;
}

export interface FluffyAttributes {
  name:              string;
  alternativeText:   null;
  caption:           null;
  width:             number;
  height:            number;
  formats:           Formats;
  hash:              string;
  ext:               string;
  mime:              string;
  size:              number;
  url:               string;
  previewUrl:        null;
  provider:          string;
  provider_metadata: ProviderMetadata;
  createdAt:         string;
  updatedAt:         string;
}

export interface Formats {
  large:     Large;
  small:     Large;
  medium:    Large;
  thumbnail: Large;
}

export interface Large {
  ext:               string;
  url:               string;
  hash:              string;
  mime:              string;
  name:              string;
  path:              null;
  size:              number;
  width:             number;
  height:            number;
  provider_metadata: ProviderMetadata;
}

export interface ProviderMetadata {
  public_id:     string;
  resource_type: string;
}

export interface Meta {
}
